<?php
//Rename this file to secret.php after all fields have been entered

$secret = 'oauth:xxx'; /* Get your Chat OAuth Password here => https://twitchapps.com/tmi/ */

$bot_id = ''; // Obtained from https://dev.twitch.tv/console/apps
$bot_secret = ''; // Obtained from https://dev.twitch.tv/console/apps

if($token_blob = file_get_contents(getcwd().'/temp/access_token.php')) $bot_token = unserialize($token_blob);
else $bot_token = ''; // Obtained from your own server using twitch_oauth.php

if($refresh_blob = file_get_contents(getcwd().'/temp/refresh_token.php')) $refresh_token = unserialize($refresh_blob);
else $refresh_token = ''; // Obtained from your own server using twitch_oauth.php

if($expires_blob = file_get_contents(getcwd().'/temp/expires_time.php')) $expires_in = unserialize($expires_blob);
else $expires_time = time()-5; // Generated by Helix.php, this currently just forces fetching of new tokens on runtime if the true $expires_time is unknown internally. No need to change this...

$expires_in = '13129'; // Obtained from your own server using twitch_oauth.php (Will be fully deprecated soon)
$scope = ["user:edit","user:read:email","viewing_activity_read"];
$token_type = "bearer"; //DO NOT CHANGE!
?>
